version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: banid
      POSTGRES_PASSWORD: 4321
      POSTGRES_DB: blogdb
    ports:
    - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
